- name: Generar hash del password
  command: "openssl passwd -6 {{ password }}"
  register: password_hash_cmd
  changed_when: false

- name: Crear usuario con su home
  become: yes
  ansible.builtin.user:
    name: "{{ usuario }}"
    groups: "{{ grupo | default('users') }}"
    append: yes
    password: "{{ password_hash_cmd.stdout }}"
    create_home: yes
  register: output_usuario

- name: Usuario creado
  debug:
    msg: "✅ Usuario '{{ usuario }}' creado correctamente"
  when: output_usuario.changed

- name: Usuario ya existía
  debug:
    msg: "ℹ️ El usuario '{{ usuario }}' ya existía"
  when: not output_usuario.changed